The output layer of PUDL compiles many tables and generates less normalized (more spreadsheet-like, less database-like) tables. Some of these output tables include derived values. If you want to see any of the processing that has been done to the original PUDL tables, check out `pudl/output` and `pudl/analysis/mcoe`. 

If you want to generate all of the csv's, you can press the ⏩ button or select 'Kernal > Resart & Run All'.

In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import pudl
import pudl.constants as pc

Here we are generating the PUDL output object. Right now, it is set up with a monthly frequency (freq="MS"), but if you want an annual frequency you can change this to "AS". You can also constrain the data range with agruments like start_date="2012-01-01" and end_date="2017-12-31".

In [2]:
pudl_out = pudl.output.pudltabl.PudlTabl(freq="MS")

Here is a list of the output objects elements that can be used to grab some of the compiled tables.

In [79]:
elements = [ x for x in dir(pudl_out) if ("__" not in x) and
            (x not in ['_dfs', 'freq','end_date','start_date','testing',]) ]
print(elements)

['bf_eia923', 'bga', 'bga_eia860', 'capacity_factor', 'fbp_ferc1', 'frc_eia923', 'fuel_cost', 'fuel_ferc1', 'gen_eia923', 'gens_eia860', 'gf_eia923', 'hr_by_gen', 'hr_by_unit', 'mcoe', 'own_eia860', 'plants_eia860', 'plants_steam_ferc1', 'pu_eia860', 'pu_ferc1', 'utils_eia860']

## CSV export for output tables

Below we'll generate csv's for each of the pudl output tables. These should show up in this folder. If you want to see or select any records from any of the tables, you can see the examples in the Boiler Generator Association section.

#### Boiler Generator Associations

In [8]:
boiler_gen_associations_df = pudl_out.bga()
boiler_gen_associations_df.to_csv('boiler_generator_association.csv',index=False,)

In [42]:
# head give the top records of the dataframe. 
# Without a number in the parentheses, it will return 5 records, but you can change the 3 below.
boiler_gen_associations_df.head(3)

,id,plant_id_eia,report_date,generator_id,boiler_id,unit_id_eia,unit_id_pudl,bga_source
0,1,3,2016-01-01,1,1,None,1,eia860_org
1,2,3,2016-01-01,2,2,None,2,eia860_org
2,3,3,2016-01-01,3,3,None,3,eia860_org

In [35]:
# this returns a random sample of records
boiler_gen_associations_df.sample(5)

,id,plant_id_eia,report_date,generator_id,boiler_id,unit_id_eia,unit_id_pudl,bga_source
9636,9637,10822,2012-01-01,GEN1,BOIL1,None,1,eia860_org
3574,3575,3006,2011-01-01,3,3,None,3,eia860_org
14418,14419,52176,2017-01-01,GEN3,GEN1,CC1,1,eia860_org
19033,19034,55299,2015-01-01,ST-1,HRSG1,CC1,1,eia860_org
288,289,271,2011-01-01,5,5,None,1,eia860_org

In [34]:
# if you care about a specifc plant and you know the plant id from EIA, you can select just that plant
boiler_gen_associations_df[boiler_gen_associations_df['plant_id_eia'] == 117]

,id,plant_id_eia,report_date,generator_id,boiler_id,unit_id_eia,unit_id_pudl,bga_source
132,133,117,2016-01-01,1B,1B,None,1,eia860_org
133,134,117,2016-01-01,2B,2B,None,2,eia860_org
134,135,117,2016-01-01,3B,3B,None,3,eia860_org
135,136,117,2016-01-01,C4-2,CC4,CC1,4,eia860_org
136,137,117,2016-01-01,C4-2,C4-1,CC1,4,eia860_org
137,138,117,2016-01-01,C4-1,CC4,CC1,4,string_assn
138,139,117,2016-01-01,C4-1,C4-1,CC1,4,string_assn
139,140,117,2016-01-01,C5-3,CC5B,CC2,5,eia860_org
140,141,117,2016-01-01,C5-3,CC5A,CC2,5,eia860_org
141,142,117,2016-01-01,C5-3,C5-1,CC2,5,eia860_org
142,143,117,2016-01-01,C5-3,C5-2,CC2,5,eia860_org
143,144,117,2016-01-01,C5-1,CC5B,CC2,5,string_assn
144,145,117,2016-01-01,C5-1,CC5A,CC2,5,string_assn
145,146,117,2016-01-01,C5-1,C5-1,CC2,5,string_assn
146,147,117,2016-01-01,C5-1,C5-2,CC2,5,string_assn
147,148,117,2016-01-01,C5-2,CC5B,CC2,5,string_assn
148,149,117,2016-01-01,C5-2,CC5A,CC2,5,string_assn
149,150,117,2016-01-01,C5-2,C5-1,CC2,5,string_assn
150,151,117,2016-01-01,C5-2,C5-2,CC2,5,string_assn
151,152,117,2017-01-01,1B,1B,None,1,eia860_org
152,153,117,2017-01-01,2B,2B,None,2,eia860_org
153,154,117,2017-01-01,3B,3B,None,3,eia860_org
154,155,117,2017-01-01,C4-2,CC4,CC1,4,eia860_org
155,156,117,2017-01-01,C4-2,C4-1,CC1,4,eia860_org
156,157,117,2017-01-01,C4-1,CC4,CC1,4,string_assn
157,158,117,2017-01-01,C4-1,C4-1,CC1,4,string_assn
158,159,117,2017-01-01,C5-3,CC5A,CC2,5,eia860_org
159,160,117,2017-01-01,C5-3,CC5B,CC2,5,eia860_org
160,161,117,2017-01-01,C5-3,C5-1,CC2,5,eia860_org
161,162,117,2017-01-01,C5-3,C5-2,CC2,5,eia860_org
...,...,...,...,...,...,...,...,...
140,141,117,2010-01-01,C5-3,CC5A,CC2,5,eia860_org
141,142,117,2010-01-01,C5-3,C5-1,CC2,5,eia860_org
142,143,117,2010-01-01,C5-3,C5-2,CC2,5,eia860_org
143,144,117,2010-01-01,C5-1,CC5B,CC2,5,string_assn
144,145,117,2010-01-01,C5-1,CC5A,CC2,5,string_assn
145,146,117,2010-01-01,C5-1,C5-1,CC2,5,string_assn
146,147,117,2010-01-01,C5-1,C5-2,CC2,5,string_assn
147,148,117,2010-01-01,C5-2,CC5B,CC2,5,string_assn
148,149,117,2010-01-01,C5-2,CC5A,CC2,5,string_assn
149,150,117,2010-01-01,C5-2,C5-1,CC2,5,string_assn
150,151,117,2010-01-01,C5-2,C5-2,CC2,5,string_assn
132,133,117,2009-01-01,1B,1B,None,1,eia860_org
133,134,117,2009-01-01,2B,2B,None,2,eia860_org
134,135,117,2009-01-01,3B,3B,None,3,eia860_org
135,136,117,2009-01-01,C4-2,CC4,CC1,4,eia860_org
136,137,117,2009-01-01,C4-2,C4-1,CC1,4,eia860_org
137,138,117,2009-01-01,C4-1,CC4,CC1,4,string_assn
138,139,117,2009-01-01,C4-1,C4-1,CC1,4,string_assn
139,140,117,2009-01-01,C5-3,CC5B,CC2,5,eia860_org
140,141,117,2009-01-01,C5-3,CC5A,CC2,5,eia860_org
141,142,117,2009-01-01,C5-3,C5-1,CC2,5,eia860_org
142,143,117,2009-01-01,C5-3,C5-2,CC2,5,eia860_org
143,144,117,2009-01-01,C5-1,CC5B,CC2,5,string_assn
144,145,117,2009-01-01,C5-1,CC5A,CC2,5,string_assn
145,146,117,2009-01-01,C5-1,C5-1,CC2,5,string_assn
146,147,117,2009-01-01,C5-1,C5-2,CC2,5,string_assn
147,148,117,2009-01-01,C5-2,CC5B,CC2,5,string_assn
148,149,117,2009-01-01,C5-2,CC5A,CC2,5,string_assn
149,150,117,2009-01-01,C5-2,C5-1,CC2,5,string_assn
150,151,117,2009-01-01,C5-2,C5-2,CC2,5,string_assn

#### Boiler Fuel from EIA 923

In [6]:
boiler_fuel_eia923_df = pudl_out.bf_eia923()
boiler_fuel_eia923_df.to_csv('boiler_fuel_eia923.csv',index=False)

#### Capacity Factor

In [40]:
capacity_factor_df = pudl_out.capacity_factor()
capacity_factor_df.to_csv('capacity_factor.csv',index=False)

#### Fuel by Plant FERC1

In [45]:
fuel_by_plant_ferc1_df = pudl_out.fbp_ferc1()
fuel_by_plant_ferc1_df.to_csv('fuel_by_plant_ferc1.csv',index=False)

#### Fuel Receipts Costs EIA923

In [43]:
fuel_receipts_costs_eia923_df = pudl_out.frc_eia923()
fuel_receipts_costs_eia923_df.to_csv('fuel_receipts_costs_eia923.csv',index=False)

#### Fuel Cost

In [48]:
fuel_cost_df = pudl_out.fuel_cost()
fuel_cost_df.to_csv('fuel_cost.csv',index=False)

/Users/christinagosnell/anaconda/envs/pudl/lib/python3.6/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

#### Fuel FERC1

In [50]:
fuel_ferc1_df = pudl_out.fuel_ferc1()
fuel_ferc1_df.to_csv('fuel_ferc1.csv',index=False)

#### Generation EIA 923

In [51]:
gen_eia923_df = pudl_out.gen_eia923()
gen_eia923_df.to_csv('generation_eia923.csv',index=False)

#### Generators EIA 860

In [53]:
gens_eia860_df = pudl_out.gens_eia860()
gens_eia860_df.to_csv('generators_eia860.csv',index=False)

#### Generation Fuel EIA 923

In [56]:
gf_eia923_df = pudl_out.gf_eia923()
gf_eia923_df.to_csv('generator_fuel_eia923.csv',index=False)

#### Hear Rate By Generator

In [58]:
hr_by_gen_df = pudl_out.hr_by_gen()
hr_by_gen_df.to_csv('heat_rate_by_gen.csv',index=False)

#### Marginal Cost of Electricity

In [60]:
mcoe_df = pudl_out.mcoe()
mcoe_df.to_csv('marginal_cost_of_electricity.csv',index=False)

#### Ownership EIA 860

In [62]:
own_eia860_df = pudl_out.own_eia860()
own_eia860_df.to_csv('ownership_eia860.csv',index=False)

#### Plants EIA 860

In [64]:
plants_eia860_df = pudl_out.plants_eia860()
plants_eia860_df.to_csv('plants_eia860.csv',index=False)

#### Steam Plants FERC1

In [66]:
plants_steam_ferc1_df = pudl_out.plants_steam_ferc1()
plants_steam_ferc1_df.to_csv('plants_steam_ferc1.csv',index=False)

#### Plant Utility Associations EIA 860

In [70]:
pu_eia860_df = pudl_out.pu_eia860()
pu_eia860_df.to_csv('plant_utility_associations_eia860.csv',index=False)

#### Plant Utility Associations EIA 860

In [72]:
pu_ferc1_df = pudl_out.pu_ferc1()
pu_ferc1_df.to_csv('plant_utility_associations_ferc1.csv',index=False)

#### Utilities EIA 860

In [75]:
utils_eia860_df = pudl_out.utils_eia860()
utils_eia860_df.to_csv('utilities_eia860.csv',index=False)